var data={
	code:1, 
	list:[
		{
			smallsrc:["smallPic/list-img16.jpg","smallPic/list-img17.jpg","smallPic/list-img18.jpg","smallPic/list-img19.jpg","smallPic/list-img20.jpg","smallPic/list-img21.jpg","smallPic/list-img46.jpg","smallPic/list-img52.jpg"],
			src:["img/list-img16.jpg","img/list-img17.jpg","img/list-img18.jpg","img/list-img19.jpg","img/list-img20.jpg","img/list-img21.jpg","img/list-img46.jpg","img/list-img52.jpg"],
			title:["1111","2222","3333"]
		},
		{
			smallsrc:["smallPic/list-img22.jpg","smallPic/list-img23.jpg","smallPic/list-img24.jpg","smallPic/list-img25.jpg","smallPic/list-img26.jpg","smallPic/list-img27.jpg","smallPic/list-img47.jpg","smallPic/list-img53.jpg"],
			src:["img/list-img22.jpg","img/list-img23.jpg","img/list-img24.jpg","img/list-img25.jpg","img/list-img26.jpg","img/list-img27.jpg","img/list-img47.jpg","img/list-img53.jpg"],
			title:["1111","2222","3333"]
		},
		{
			smallsrc:["smallPic/list-img28.jpg","smallPic/list-img29.jpg","smallPic/list-img30.jpg","smallPic/list-img31.jpg","smallPic/list-img32.jpg","smallPic/list-img33.jpg","smallPic/list-img48.jpg","smallPic/list-img54.jpg"],
			src:["img/list-img28.jpg","img/list-img29.jpg","img/list-img30.jpg","img/list-img31.jpg","img/list-img32.jpg","img/list-img33.jpg","img/list-img48.jpg","img/list-img54.jpg"],
			title:["1111","2222","3333"]
		},
		{
			smallsrc:["smallPic/list-img34.jpg","smallPic/list-img35.jpg","smallPic/list-img36.jpg","smallPic/list-img37.jpg","smallPic/list-img38.jpg","smallPic/list-img39.jpg","smallPic/list-img49.jpg","smallPic/list-img55.jpg"],
			src:["img/list-img34.jpg","img/list-img35.jpg","img/list-img36.jpg","img/list-img37.jpg","img/list-img38.jpg","img/list-img39.jpg","img/list-img49.jpg","img/list-img55.jpg"],
			title:["1111","2222","3333"]
		},
		{
			smallsrc:["smallPic/list-img40.jpg","smallPic/list-img41.jpg","smallPic/list-img42.jpg","smallPic/list-img43.jpg","smallPic/list-img44.jpg","smallPic/list-img45.jpg","smallPic/list-img50.jpg","smallPic/list-img51.jpg"],
			src:["img/list-img40.jpg","img/list-img41.jpg","img/list-img42.jpg","img/list-img43.jpg","img/list-img44.jpg","img/list-img45.jpg","img/list-img50.jpg","img/list-img51.jpg"],
			title:["1111","2222","3333"]
		}
	]
}
