var datas = {
	"worksData":[
		{
			"workPic":"img/spic1.jpg",
			"workName":"汇爱婚礼",
			"workDate":"2016-01-31",
			"workType":"企业集团"
		},{
			"workPic":"img/spic2.jpg",
			"workName":"Estor鲸鲨官网",
			"workDate":"2015-07-16",
			"workType":"企业集团"
		},{
			"workPic":"img/spic3.jpg",
			"workName":"神灯理财",
			"workDate":"2016-02-14",
			"workType":"企业集团"
		},{
			"workPic":"img/spic4.jpg",
			"workName":"悠怡蓝海 pure blue",
			"workDate":"2015-04-29",
			"workType":"企业集团"
		},{
			"workPic":"img/spic5.jpg",
			"workName":"因果树",
			"workDate":"2016-01-11",
			"workType":"门户电商"
		},{
			"workPic":"img/spic6.jpg",
			"workName":"Dentsu",
			"workDate":"2015-07-30",
			"workType":"企业集团"
		},{
			"workPic":"img/spic7.jpg",
			"workName":"movie media",
			"workDate":"2015-03-02",
			"workType":"企业集团"
		},{
			"workPic":"img/spic8.jpg",
			"workName":"BIAD 北京建筑设计研究院",
			"workDate":"2016-04-11",
			"workType":"企业集团"
		},{
			"workPic":"img/spic9.jpg",
			"workName":"黑金时尚-尚雯婕",
			"workDate":"2016-01-01",
			"workType":"企业集团"
		},{
			"workPic":"img/spic10.jpg",
			"workName":"JCD-崔友光设计事务所",
			"workDate":"2015-03-17",
			"workType":"企业集团"
		},{
			"workPic":"img/spic11.jpg",
			"workName":"宇宙企画",
			"workDate":"2015-10-13",
			"workType":"其他网页"
		},{
			"workPic":"img/spic12.jpg",
			"workName":"UEMO网页设计",
			"workDate":"2016-01-31",
			"workType":"其他网页"
		}
	],
	"serviceData":[{
		"serviceName":"服务项目",
		"serviceContent":"<img src='img/xiangmu.gif'>"
	},{
		"serviceName":"服务流程",
		"serviceContent":"<img src='img/liucheng.gif'>"
	},{
		"serviceName":"服务客户",
		"serviceContent":"<img src='img/customer.gif'>"
	}],
	"companyInfo":{
		"companyName":"北京优艺客文化传播有限公司",
		"companyAddress":"北京市通州区新华大街北京ONE写字楼2605",
		"postcode":"101100",
		"tel":"010-69557550/010-56078880",
		"phone":"13811334772 / 18611811021",
		"qq":"407280793/1252803667",
		"email":"uelike@uelike.com",
		"website":"http://www.uehtml.com",
		"aboutUs":"<p>优艺客(UElike)文化传播有限公司(原韩雪冬网页设计工作室)，成立于2008年，是由一群有着研发精神和创新精神的团队组成。<br><br>多年来，我们一直专注于互联网整合营销传播服务，截止目前我们已经服务过300多个大型客户。不论是品牌官网、企业官网、还是信息应用平台，我们都能提供精确的策划方案和视觉设计方案。无论是策略创意还是视觉执行，我们都比传统的互联网公司有着更高的造诣。我们有国际化意识和前瞻性思维；我们有策略性的创意和精美的视觉；我们能主动挖掘客户优势并进行整理、包装与有效地传播。我们追逐在互联网最前沿；我们能洞察互联网发展与审美趋势。<br><br>提升客户品牌形象、实现客户的商业目标是优艺客(UElike)永恒的追求！</p>"
	},
	"newsData":[{
			"title":"UEMO——优艺客旗下高端模板平台",
			"img":"img/uemo.jpg",
			"description":"10年建站经验 + 500家企业客户 + 顶尖建站团队 = UEMO高端企业模板。 打造出适合中小企业的高端企业模板-UEMO，精致的设计，人性化的后台，让UEMO成为您建站的首选。",
			"link":"http://www.uemo.net"
		},{
			"title":"UEhtml设计师交流平台",
			"img":"img/1.gif",
			"description":"优艺客旗下——UEhtml设计交流平台，专注于网页界面设计。为国内设计师和客户提供最优质的资源分享",
			"link":"http://www.uehtml.com"
		}
	],
	"wrapbox":[{
				"pic":"img/slide1.jpg",
				"title":"汇爱婚礼",
				"link":"#1"
			},{
				"pic":"img/slide2.jpg",
				"title":"汇爱婚礼",
				"link":"#1"
			},
			{
				"pic":"img/slide3.jpg",
				"title":"汇爱婚礼",
				"link":"#1"
			}
	]

}
